name: Deploy AWS Infra
on:
  - pull_request
env:
  tf_version: '1.5.7'
  tg_version: '0.53.2'
  working_dir: 'prod'
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_V2 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_V2 }}
          aws-region: eu-west-1
          
      - name: install and plan terragrunt
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'plan'
          if: github.ref == 'refs/heads/main'
          
      - name: Deploy
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'apply'

      - name: Save Terraform outputs
        id: set_outputs
        run: |
          echo "S3_BUCKET_NAME=$(terraform output -json aws_s3_bucket)" >> $GITHUB_ENV
          echo "CLOUDFRONT_URL=$(terraform output -json aws_cloudfront_distribution_URL)" >> $GITHUB_ENV
        working-directory: ${{ env.working_dir }}
        shell: bash
        

        
    
