name: Deploy AWS Infra
on: 
  push:
    branches:
      - main

env:
  tf_version: '1.5.7'
  tg_version: '0.53.2'
  working_dir: 'prod'
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_V2 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_V2 }}
          aws-region: eu-west-1

      - name: Install and plan terragrunt
        id: plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'plan'
        if: github.ref == 'refs/heads/main'

      - name: Deploy
        uses: gruntwork-io/terragrunt-action@v2
        with:
          terraform_wrapper: false
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'apply'

      - name: Save Terraform outputs
        run: |
            echo "$(terraform output aws_s3_bucket | tr -d '"')" >> s3_bucket.txt
            echo "$(terraform output aws_cloudfront_distribution_URL | tr -d '"')" >> cloudfront_id.txt
        working-directory: ${{ env.folder }}

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          working-directory:  ${{ env.folder }}
    
      - name: Run Python Script
        working-directory: ${{ env.folder }}
        run: |
          export S3_BUCKET_NAME=$(cat s3_bucket.txt)
          export CLOUDFRONT_URL=$(cat cloudfront_id.txt)
          python3 testing_terrgr_ver.py
