name: Deploy AWS Infra
on:
  push:
    branches:
      - dev

env:
  tf_version: '1.5.7'
  tg_version: '0.50.8'
  live_dir: 'live/prod/eu-west-1'
  owner: "eladbe96"
  repo: "p81-CloudFront"
  api_version: "2022-11-28"
  token: ${{ secrets.GIT_TOKEN }}

  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install requests boto3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_V2 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_V2 }}
          aws-region: eu-west-1

      - name: plan s3 - terragrunt
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.live_dir }}/s3
          tg_command: 'plan'
        if: github.ref == 'refs/heads/main'

      - name: apply s3 - terragrunt
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.live_dir }}/s3
          tg_command: 'apply'

      - name: plan cloudfront - terragrunt
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.live_dir }}/cloudfront
          tg_command: 'plan'
        if: github.ref == 'refs/heads/main'

      - name: apply cloudfront - terragrunt
        uses: gruntwork-io/terragrunt-action@v2
        env: 
          INPUT_POST_EXEC_1: |
            export CLOUDFRONT_URL=$(terragrunt output -raw aws_cloudfront_distribution_URL | tr -d '"')
          INPUT_POST_EXEC_2: |
            curl -L \
              -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ env.token }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ env.owner }}/${{ env.repo }}/actions/variables/CLOUDFRONT_URL \
              -d '{"name":"CLOUDFRONT_URL","value":"'"$CLOUDFRONT_URL"'"}'
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.live_dir }}/cloudfront
          tg_command: 'apply'
          
      - name: plan s3 policy - terragrunt
        id: plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.live_dir }}/policy
          tg_command: 'plan'
        if: github.ref == 'refs/heads/main'

      - name: apply s3 policy - terragrunt
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.live_dir }}/policy
          tg_command: 'apply'

      - name: run python script
        run: |
          python3 app/main.py

        



 
