name: download the file
on:
  workflow_dispatch

jobs:
    download:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Python Script
        run: |
          export COMMIT_SHA=${{ github.sha }}
          export CLOUDFRONT_URL=${{ vars.CLOUDFRONT_URL }}
          python3 app/main.py
        
