name: Download the file from CloudFront
on:
  workflow_dispatch
jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Python Script
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: Install dependencies
        run: |
          pip install boto3 requests
      - name: Run Python Script
        run: |
          python app/main.py
